site_name: Aquea
site_url: https://mkworldwide.github.io/aquea
repo_url: https://github.com/MKWorldWide/Aquea
repo_name: MKWorldWide/Aquea

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  icon:
    logo: material/water

  favicon: assets/favicon.ico

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_root_heading: true
            show_source: true
  - mkdocstrings
  - mkdocs-material
  - mike

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
  - Architecture:
      - Overview: architecture/overview.md
      - Services: architecture/services.md
      - Data Flow: architecture/data-flow.md
  - Development:
      - Setup: development/setup.md
      - Testing: development/testing.md
      - Deployment: development/deployment.md
  - API Reference:
      - Gateway: api/gateway.md
      - ML Service: api/ml-service.md
  - Contributing:
      - Guidelines: contributing/guidelines.md
      - Code of Conduct: contributing/code-of-conduct.md

extra_css:
  - css/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/extra.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MKWorldWide/Aquea
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mkworldwide
    - icon: fontawesome/solid/globe
      link: https://mkworldwide.io

copyright: Copyright &copy; 2025 MK Worldwide
